### PR TITLE
Add JSoC and OWASP Code Sprint

### PR DESCRIPTION
**Pull request by emetowinner**
fixed issue #54 
# If you are adding a SoC/WoC, please make sure 
- [ ] You have added the SoC/WoC in README.md file in correct table
- [ ] You have added the SoC/WoC in index.html in correct table
- [ ] ensure Website is tested on a deployment and looks okay

### If you are fixing an issue please add
- [ ] fixes issue #issue_number to PR description

### CODE REVIEW

**Comment by emetowinner** [comment]
@tapaswenipathak if merged, try help in closing the issue.

**Comment by emetowinner** [comment]
No I don't think so, is there. Under the Outreacy internship comes RGSOC

**Comment by tapaswenipathak** [comment]
Screenshot_20190603-084428_Chrome

**Comment by tapaswenipathak** [comment]
Screenshot_20190603-085337_Chrome

**Comment by emetowinner** [comment]
Corrected it

**Pull request merged**
