### PR TITLE
The X.Org Endless Vacation of Code (EVoC)

### PR DESCRIPTION
**Pull request by emetowinner**
### If you are adding a SoC/WoC, please make sure 
- [ ] You have added the SoC/WoC in README.md file in correct table
- [ ] You have added the SoC/WoC in index.html in correct table
- [ ] ensure Website is tested on a deployment and looks okay

### If you are fixing an issue please add
- [ ] fixes issue #issue_number to PR description

### CODE REVIEW

**Comment by emetowinner** [comment]
Some of the internship present in the readme doesn't have a timeline, am adding the timeline or shouldn't i?

**Comment by tapaswenipathak** [comment]
This is GSoC timeline I think https://summerofcode.withgoogle.com/how-it-works/#timeline.

**Comment by emetowinner** [comment]
IMG_20190529_183712_145
The dotted has no timeline, but all has a standard timeline. I was trying to add it, shouldn't i?

**Comment by tapaswenipathak** [comment]
ok go for it! :) Sorry my bad. :zap:

**Comment by tapaswenipathak** [comment]
ok go for it! Sorry my bad. ⚡️

**Comment by tapaswenipathak** [comment]
ok go for it! My bad. ⚡️

**Comment by emetowinner** [comment]
Ok 😊

**Pull request merged**
