### PR TITLE
adding Groceristar company

### PR DESCRIPTION
**Pull request by atherdon**
### If you are adding a SoC/WoC, please make sure 
- [x] You have added the SoC/WoC in README.md file in correct table
- [x] You have added the SoC/WoC in index.html in correct table
- [ ] ensure Website is tested on a deployment and looks okay

### If you are fixing an issue please add
- [ ] fixes issue #issue_number to PR description

in order to contribute back - I add your repository to my article. you can take a look here: https://hackernoon.com/looking-for-a-tech-internship-try-this-list-of-online-resources-83ae85af44

### CODE REVIEW

**Comment by atherdon** [comment]
i'm running open source projects and ready to teach students

>

**Comment by tapaswenipathak** [comment]
On Mon, 3 Jun 2019, 19:45 Arthur Tkachenko <notifications@github.com wrote:

> i'm running open source projects and teach students
>

This list lists Summer of Code/Winter of Code events/programs. Closing.

**Comment by atherdon** [comment]
as you wish. thanks for this opportunity

>

**Comment by tapaswenipathak** [comment]
On Mon, 3 Jun 2019, 19:52 Arthur Tkachenko <notifications@github.com wrote:

> as you wish. thanks for this
>

ok, np, wc. :)

**Pull request closed without merging**
